### PR TITLE
[setup] Improve setup.py

### LINKED ISSUE #101: Dependencies on sortinghat and MySQLdb not declared
Noticed this when running the tests in a build environment. They should be in install_requires or extras_requires

### PR DESCRIPTION
**Pull request by jgbarah**
Add some parameters to setup.py, including extras_require (for sortinghat and arthur), and fix minor issue with generation of README.rst.

Closes #101.

### CODE REVIEW

**Comment by jgbarah** [comment]
@sebix said:

> Some files depend on MySQLdb, which is still not required:

MySQLdb should be pulled in by SortingHat. Does it not work that way for you? (in fact, MySQLdb is only needed by SortingHat...)

**Comment by sebix** [comment]
No. MySQLdb is a depedency of this package and should be declared as such.

Additionally, sorthinghat is only an optional dependency.

**Comment by jgbarah** [comment]
I cannot figure out why grimoire-elk should ever use MySQLdb, except for dealing with SortingHat. I will have a look to check what's happening... Thanks for the heads up, @sebix.

**Comment by sebix** [comment]
> I cannot figure out why grimoire-elk should ever use MySQLdb,

In grimoire_elk/elk/database.py you are using it. Whenever you import that module, you'd get an ImportError if you do not have that library.

**Comment by jgbarah** [comment]
OK, for now, I've added a new extra dependency on `PyMySQL`, since `MySQLDB` doesn't work with Python3 (AFAIK). In any case, my impression is that we're not using SQL from `GrimoireELK` anymore, and that functionality is now in `mordred`. I will check, and maybe submit a pr later removing that, if I'm right.

**Pull request merged**
